name: web-app
version: 0.1.0.0
synopsis: My Haskell project
description: See report.pdf
maintainer: Maurits Dijk <m.r.dijk@uva.nl>
category: Logic

ghc-options: -Wall

dependencies:
  - base
  - random
  - QuickCheck
  - aeson
  - scotty
  - wai-cors
  

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - web-app

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - report
      - QuickCheck
      - hspec
